### ISSUE TITLE
Ability to specify other Folder than App\Nova\Dashboard?

### ISSUE THREAD

**Issue by shirshak55** [alexbowers/nova-multiple-dashboard#1]
Sometime we use modular laravel so there is no App folder at root directory like normal laravel installation. So is there anyway to handle those error like App namespace not found ?

Thanks

**Comment by alexbowers** [comment]
Where would the dashboards be stored for you? IN one of the modules with a Dashboard directory?

The code as it stands handles there being a different namespace for the dashboards, but it is currently expecting there to be a `App/Nova` path.

I can change that to be a config value that gets passed in, or I can change it so that it only autoloads those in if there is a directory that exists for `App/Nova/Dashboards`.

To load them in yourself you'd need to use your own ServiceProvider and call 

```
\AlexBowers\MultipleDashboard\DashboardNova::registerDashboards(new \Your\Dashboard\Here);
```

yourself to register them all.

**Comment by shirshak55** [comment]
Update:

Yea it works perfectly. Thanks

**Comment by shirshak55** [comment]
Yea config would be better choice too :)
